# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70fde6f66a921e6829d0d2acdf3c757760a8ec2ef7de769583c52355f839942a5bc9cb8e2655e9c1b48342aec12b79fda930be96b08eb035ced82232980d3c17

test:
  secret_key_base: 316ef19a7aa63f2fd968227b7c94bdb81831b62e29ad07be9de6cf7282f38c79af1ae29c41f1f1ec378f54090b62aac156e5f4742609e0f6c3450c2b89ecf9e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
